### ISSUE TITLE
IndexError: list index out of range.

### ISSUE THREAD

**Issue by tenderzada** [Digital-Twin-Operational-Platform/Cristallo#8]
hi~，Cristallo is a great job.
When I try to run flask this error occurs causing me to not be able to continue, can you please give me some help.
![微信图片_20220518170355](https://user-images.githubusercontent.com/44317940/169002349-cfe51d09-b944-418c-b8fc-4db2124c6dd8.png)

**Comment by marcodeangelis** [comment]
Thanks for reaching out and telling us about this error.

I guess what is causing your error is the absence of the `.git` folder in you repository, which is legitimate if you opt for downloading the software rather than git-cloning it. We do not get many users outside the development team, so we hadn't really encountered this problem before. 

I will drop one more comment when this issue has been addressed.

**Comment by marcodeangelis** [comment]
The git repository is now created upon `flask run` when the user downloads the zip file. However, the user must have Git installed.

So this particular issue is now resolved.
